<p class='notebook_header'><b>CS 309 - Robot Learning</b></p>
<p class='notebook_header'>Python Tutorial</p>

<hr class='separate' />

<p style="color:red"><b>IMPORTANT: Make sure you've gone through Conda_Tutorial first before continuing here (should be in same folder).</b></p>

<p style="color:red"><b>IMPORTANT: Make sure you're viewing this file locally on your computer, not via GitHub. Go back to the last notebook if you missed that step.</b></p>

<p><b>Contents</b></p>
<ol style="float: left;">
    <li><a href="#background">Python Background</a></li>
    <li><a href="#variables">Variables</a></li>
    <li><a href="#operators">Operators</a></li>
    <li><a href="#functions">Functions</a></li>
    <li><a href="#scope">Scope</a></li>
    <li><a href="#collections">Collections</a></li>
    <li><a href="#loops">Loops</a></li>
    <li><a href="#logic">Logic</a></li>
    <li><a href="#identity">Identity</a></li>
    <li><a href="#conditions">Conditions</a></li>
    <li><a href="#loops_revisited">Loops (Revisited)</a></li>
</ol>

<ol start="12" style="float: left;">
    <li><a href="#list_comp">List Comprehension</a></li>
    <li><a href="#membership">Membership</a></li>
    <li><a href="#classes">Classes</a></li>
    <li><a href="#duck_typing">Duck Typing</a></li>
    <li><a href="#casting">Casting</a></li>
    <li><a href="#exceptions">Exceptions</a></li>
    <li><a href="#modules">Modules</a></li>
    <li><a href="#numpy">Numpy (in a nutshell)</a></li>
    <li><a href="#mutables">Mutables as default values in functions</a></li>
    <li><a href="#wrap_up">Wrap Up</a></li>
</ol>

<p class='section_header' id="background"><b>1. Python Background</b></p>

<p>Python started in December 1989 as a "hobby project" of Guido Van Rossum. The goal was to develop a <b>powerful, open source, easy and intuitive</b> programming language. By now Python is one of the <b>most taught and used programming language</b> world wide.</p>

<p><b>Used in</b>: OS level scripts, web dev, database systems, data science, robotics, ...</p>

<p><b>Python as a language:</b></p>
<ul>
    <li>more readable than most other programming languages</li>
    <li>ends statements at the end of a line, instead of semicolons</li>
    <li>defines the current scope based on indentation, instead of brackets</li>
</ul>

<p><b>Python runs on an interpreter:</b></p>
<ul>
    <li>platform independent (Linux, Windows, Mac, ...)</li>
    <li>no compilation</li>
    <li>great for rapid prototyping</li>
</ul>

<p><b>Python is very versatile:</b></p>
<ul>
    <li>can be used in a procedural, functional, or object-oriented way</li>
    <li>can be used in an text editor e.g., vim, nano, gedit, atom</li>
    <li>or in an advanced Integrated Development Environment e.g., eclipse, pycharm</li>
    <li>and even in interactive websites and lectures e.g., jupyter-notebook</li>
</ul>

<p><b>Two major versions of Python:</b></p>
<ul>
    <li>Python 2 (2.7.?)</li>
    <ul>
        <li>Supported until 2020</li>
    </ul>
    <br>
    <li>Python 3 (3.8.?)</li>
    <ul>
        <li>Improved performance</li>
        <li>Slightly changed syntax</li>
        <li>Will be used in this lecture</li>
    </ul>
</ul>

<p class='section_header' id="variables"><b>2. Variables</b></p>

<p><b>Variable Names:</b></p>
<ul>
    <li>have to start with a letter</li>
    <li>or an underscore</li>
    <li>or certain unicode symbols (python 3!)</li>
</ul>

In [3]:
aVariable = "hello"
_secret_ = 222
π = 3.14
α = 3/5*π

print(α)

1.884


<p>Python does <b>not require type declaration</b>, i.e., you don't need to define variable types like int, float, string, etc. This does not mean Python doesn't have types! It just "assumes" the type of the variable given the value. You can just assign <b>any value</b> to <b>any variable</b>.</p>

In [4]:
# Notice we keep scope from previous cells as long as those
# cells been run in this instance of Jupyter Notebook.

type(aVariable)

str

<p class='section_header' id="operators"><b>3. Operators</b></p>

<p><b>Common Operators:</b></p>
<table style="width:60%;">
  <tr>
    <td>Addition</td>
    <td>+</td>
  </tr>
  <tr>
    <td>Subtraction</td>
    <td>-</td>
  </tr>
  <tr>
    <td>Multiplication</td>
    <td>*</td>
  </tr>
  <tr>
    <td>Division</td>
    <td>/</td>
  </tr>
  <tr>
    <td>Modulus</td>
    <td>%</td>
  </tr>
  <tr>
    <td>Exponentiation</td>
    <td>**</td>
  </tr>
  <tr>
    <td>Floor Division</td>
    <td>//</td>
  </tr>
</table>

In [5]:
var = 123
print("Original:", var)
print("Addition:", var + 2)
print("Subtraction:", var - 2)

Original: 123
Addition: 125
Subtraction: 121


In [6]:
print("Modulus:", var % 120)

print("Multiplication:", var * 2)
print("Exponentiation:", var ** 2)

print("Division:", var / 10)
print("Floor Division:", var // 10)

Modulus: 3
Multiplication: 246
Exponentiation: 15129
Division: 12.3
Floor Division: 12


<p><b>Less Common Operators:</b></p>
<table style="width:60%;">
  <tr>
    <td>AND</td>
    <td>&</td>
  </tr>
  <tr>
    <td>OR</td>
    <td>|</td>
  </tr>
  <tr>
    <td>XOR</td>
    <td>^</td>
  </tr>
  <tr>
    <td>NOT</td>
    <td>~</td>
  </tr>
  <tr>
    <td>Zero fill left shift</td>
    <td><<</td>
  </tr>
  <tr>
    <td>Signed right shift</td>
    <td>>></td>
  </tr>
</table>

<p>You can also combine any of he previous operators with the assignment operator to save some typing.</p>
<ul>
    <li>a += b is equal to a = a+b</li>
</ul>

<p class='section_header' id="functions"><b>4. Functions</b></p>

<p>Functions are defined using the keyword <b>def</b>. After the name of the function all expected parameters are listed within parenthesis:</b></p>
<div class="code-div"><code>def func_name(param1, param2)</code></div>

<p>If you have default values for the prameters you can assign them in the function definition:</p>
<div class="code-div"><code>def func_name(param1, param=default_value)</code></div>

<p>Python also provides anonymous (lambda) functions:</p>
<div class="code-div"><code>sqr = lambda x: x**2</code></div>

In [7]:
def increase_var_by_one(var_input=0):
    return var_input + 1

lambda_func = lambda input: input + 2

var = 10

# Supplying var to function.
print("Using function:", increase_var_by_one(var))

# Letting function use default value.
print("Using function with default arg:", increase_var_by_one())

# Supplying var to lambda function.
print("Using lambda:", lambda_func(var))

Using function: 11
Using function with default arg: 1
Using lambda: 12


<p class='section_header' id="scope"><b>5. Scope</b></p>

<p>Variables are only accessible within their scope:</p>
<ul>
    <li>Defining a variable outside of any function/class creates a <b>global variable</b>.</li>
    <ul>
    <li>The <code>global</code> keyword allows to access and edit global variables inside a local scope</li>
    </ul>
    <br>
    <li>Defining a variable inside a function/class creates a <b>local variable</b>.</li>
    <ul>
    <li>The <code>nonlocal</code> keyword allows to access and edit variables from encapsulating scopes (except global) to be accessed and edited by nested functions</li>
    </ul>
</ul>

In [8]:
# Statements that start with '%' are called 'IPython magic commands'.
# They are only available if an "IPython" interpreter is used as for instance in Jupyter-Notebook.
# They allow to give commands to the interperter itself.

# This specific command resets the current namespace i.e., all variables are deleted.
%reset -f

a = 'global'
b = 'global'

def func1():
    global a
    a = 'local'
    c = 'local'
    def func2():
        nonlocal c
        c = 'edited'
        a = 'edited'
        print("-- 1 --")
        print("a = {}".format(a))
        print("c = {} \n".format(c))
        
    func2()
    print("-- 2 --")
    print("a = {}".format(a))
    print("b = {}".format(b))
    print("c = {} \n".format(c))
    
    
func1()
print("-- 3 --")
print("a = {}".format(a))
print("b = {} \n".format(b))

-- 1 --
a = edited
c = edited 

-- 2 --
a = local
b = global
c = edited 

-- 3 --
a = local
b = global 



<p class='section_header' id="collections"><b>6. Collections</b></p>

<p>Python has four basic collection types. Follow below to learn about them.</p>

<b><code>list</code></b>
<ul>
    <li>ordered, mutable, duplicate elements possible</li>
</ul>

In [9]:
# this is how you define a list
a_list = [1,2,3]
print(a_list)

# You can access the elements via indexing.
print(a_list[0])   # Indices start at 0
print(a_list[-1])  # You can index starting from the end

# You can change the elements
a_list[0] = 0
print(a_list)

# You can append (add) elements
a_list.append(5)
a_list.append('6')
a_list.append([7,8,'Nine'])
print(a_list)

# You can delete elements by index
del a_list[0], a_list[-1]
print(a_list)

# You can also extend the list with another collection
a_list.extend([10,11,12])
print(a_list)

[1, 2, 3]
1
3
[0, 2, 3]
[0, 2, 3, 5, '6', [7, 8, 'Nine']]
[2, 3, 5, '6']
[2, 3, 5, '6', 10, 11, 12]


<b><code>tuple</code></b>
<ul>
    <li>ordered, immutable, duplicates elements possible</li>
</ul>

In [10]:
# this is how you define a tuple
a_tuple = (1,'2',[3, 4])
print(a_tuple)

# You can access the elements via indexing.
print(a_tuple[0])   # Indices start at 0
print(a_tuple[-1])  # You can index starting from the end

# You can NOT change the elements
# a_tuple[0] = 0     # Throws an error.

# You can NOT append elements
# a_tuple.append(0)

# You can NOT delete elements
# del a_tuple[0]

# You can NOT extend the tuple
# a_tuple.extend(0)

(1, '2', [3, 4])
1
[3, 4]


<b><code>set</code></b>
<ul>
    <li>unordered, mutable, unique elements</li>
</ul>

In [11]:
# this is how you define a set
a_set = {1,2,3,4}
print(a_set)

# You can NOT access the elements via indexing.
# print(a_set[0])   # Throws an error.

# You can add elements, however duplicates are not added.
a_set.add(5)
a_set.add('6')
a_set.add(5)
print(a_set)

# You can only add "hashable objects"
# hashable objects: objects that don't change over lifetime

# a_set.add([1,2,3])  # lists are not hashable
# a_set.add({1,2,3})  # sets are not hashable
a_set.add((1,2,3))    # tuples are hashable
print(a_set)

# You can delete elements by value
a_set.remove(1)
print(a_set)
a_set.remove((1,2,3))

# You can also extend the set with another collection
a_set.update([5,10,11,12])
print(a_set)

{1, 2, 3, 4}
{1, 2, 3, 4, 5, '6'}
{1, 2, 3, 4, 5, '6', (1, 2, 3)}
{2, 3, 4, 5, '6', (1, 2, 3)}
{2, 3, 4, 5, '6', 10, 11, 12}


<b><code>dict</code></b>
<ul>
    <li>key-value pairs as elements</li>
    <li>keys are a set</li>
</ul>

In [12]:
# this is how you define a dictionary
a_dict = {'key':'value', 'a':7, 2:'two'}
print(a_dict)

# You can access the value using the key
print(a_dict['key'])
print(a_dict['a'])

# You can change the elements
a_dict[2] = 'zwei'
print(a_dict)

# You can add new elements
a_dict['three'] = 3

# every hashable object can be key
# and any object can be a value
a_dict[(1,2,3)] = 'look a tuple key!'
print(a_dict)

# You can delete elements using the key
del a_dict[(1,2,3)]
print(a_dict)

# You can also extend the dict with another dict
a_dict.update({4:'four','five':5})
print(a_dict)

# the keys form a set:
print(a_dict.keys())

# and the values form a list:
print(a_dict.values())

{'key': 'value', 'a': 7, 2: 'two'}
value
7
{'key': 'value', 'a': 7, 2: 'zwei'}
{'key': 'value', 'a': 7, 2: 'zwei', 'three': 3, (1, 2, 3): 'look a tuple key!'}
{'key': 'value', 'a': 7, 2: 'zwei', 'three': 3}
{'key': 'value', 'a': 7, 2: 'zwei', 'three': 3, 4: 'four', 'five': 5}
dict_keys(['key', 'a', 2, 'three', 4, 'five'])
dict_values(['value', 7, 'zwei', 3, 'four', 5])


<p class='section_header' id="loops"><b>7. Loops</b></p>

<p>Loops iterate over each element in a collection. Several different types in Python, each with their own use case.</p>

<p><code>for</code></p>
<ul>
    <li>Most common and basic looping mechanism.</li>
</ul>

In [13]:
a_list = ['a','b','c']

for an_element in a_list:
    # print('list element: {}'.format(an_element))
    print(an_element)

a
b
c


<p><code>enumerate</code></p>
<ul>
    <li>Same as <code>for</code>, but adds indices to track progression</li>
</ul>

In [14]:
a_tuple = ('d','e','f')

for an_index, an_element in enumerate(a_tuple):
    # print('tuple element[{}]: {}'.format(an_index, an_element))
    print(an_index, an_element)

0 d
1 e
2 f


<p><code>zip</code></p>
<ul>
    <li>Iterates over multiple collections at once</li>
</ul>

In [15]:
a_tuple = ('d','e','f')
a_set = {'g','h','i'}


for t_ele, s_ele in zip(a_tuple, a_set):
    print('elements: {},{}'.format(t_ele, s_ele))

print()

# You can also combine zip with enumerate.
for idx, (t_ele, s_ele) in enumerate(zip(a_tuple, a_set)):
    print('elements[{}]: {},{}'.format(idx, t_ele, s_ele))

elements: d,h
elements: e,i
elements: f,g

elements[0]: d,h
elements[1]: e,i
elements[2]: f,g


<p><code>range</code></p>
<ul>
    <li>Use if you just want to run something N times</li>
</ul>

In [16]:
for i in range(3):
    print(i)

0
1
2


<p class='section_header' id="logic"><b>8. Logic</b></p>

<table style="width:60%;">
  <tr>
    <td>Equal</td>
    <td>==</td>
  </tr>
  <tr>
    <td>Not Equal</td>
    <td>!=</td>
  </tr>
  <tr>
    <td>Greater Than</td>
    <td>></td>
  </tr>
  <tr>
    <td>Less Than</td>
    <td><</td>
  </tr>
  <tr>
    <td>Greater than or equal to</td>
    <td>>=</td>
  </tr>
  <tr>
    <td>Less than or equal to</td>
    <td><=</td>
  </tr>
</table>
<br>
<table style="width:60%;">
  <tr>
    <td>true if both sides are true</td>
    <td>and</td>
  </tr>
  <tr>
    <td>true if one side is true</td>
    <td>or</td>
  </tr>
  <tr>
    <td>negate</td>
    <td>not</td>
  </tr>
  <tr>
    <td>true if all elements of a collection are true</td>
    <td>all(...)</td>
  </tr>
  <tr>
    <td>true if any element of a collection is true</td>
    <td>any(...)</td>
  </tr>
</table>

In [17]:
print('this' == 'that') # should be False
print('this' == 'this') # should be True
print('this' == 'This') # should be False: case sensitive!
this_variable = 'this'
print('this' == this_variable) # should be True

False
True
False
True


In [18]:
a1 = 1
a2 = 1
b = 2
print(a1 == a2) # should be True
print(a1 < a2) # should be False
print(a1 < b) # should be True
print(a1 <= a2) # should be True

True
False
True
True


In [19]:
print(a1==a2 and 'this' == this_variable) # should be True since both statements are True
print(a1==a2 == 'this' == this_variable) # should be False since a2 is not equal to 'this': evaluates left to right
print((a1==a2) == ('this' == this_variable)) # should be True because the terms in parentheses take precedence

True
False
True


In [20]:
a_list = [True, True, False, True]
print(any(a_list)) # should be True
print(all(a_list)) # should be False

True
False


<p class='section_header' id="identity"><b>9. Identity</b></p>

<p>Pythons equality operator <code>==</code> compares two variables by their value. However, sometimes it is necessary to identify if two variables are actually the same variable.

There is the identity operator <code>is</code> and it's negation <code>is not</code> which check variables for identity.</p>

In [21]:
a_list = [1,2,3]
b_list = [1,2,3]

print(a_list == b_list) # should be True, since both lists have the same content
print(a_list is b_list) # should be False because they are not the same list

True
False


<p>Unfortunately python has it's quirks and one of them is that the <code>is</code> operator behaves confusingly with respect to integers and strings.

Let's compare some integers.</p>

In [22]:
a = 256
b = 256

print("a == b:", a == b) # this should be True
print("a is b:", a is b) # this should be False but it isn't!!

c = 257
d = 257

print("c == d:", c == d) # this should be True
print("c is d:", c is d) # this should be False and it is. But why?!

a == b: True
a is b: True
c == d: True
c is d: False


<p>What <code>is</code> actually does is checking the id of the variables for equality. <code>a is b</code> is the same as <code>id(a) == id(b)</code>.

Python stores integers between -5 and 256 in an internal array. If one of these values is assigned to a variable, that variable is not actually referencing some place in the memory that holds the corresponding value but instead references the corresponding entry in the internal array.

The idea behind it is to avoid allocating tons of memory that holds the same common integers over and over again, but instead allocating them once and referencing that memory whenever needed.</p>

In [23]:
a = 256
b = 256

print("id(a):",id(a))
print("id(b):",id(b))

c = 257
d = 257

print("id(c):",id(c))
print("id(d):",id(d))

id(a): 1649871280
id(b): 1649871280
id(c): 2172943904400
id(d): 2172943904144


<p>Python behaves similarly with simple strings. This is called "string interning". It's similar to the integers just a bit more complicated, and we won't go into detail.</p>

In [24]:
a = "Why"
b = "Why"

print("id(a):",id(a))
print("id(b):",id(b))

c = "Why?"
d = "Why?"

print("id(c):",id(c))
print("id(d):",id(d))

id(a): 2172944441840
id(b): 2172944441840
id(c): 2172944445368
id(d): 2172944445200


<p>If you are confused. That's alright. This is confusing and there is a reason there are entire blog posts discussing / complaining about it.

What you should take away is that while the <code>is</code> operator can be really useful for more complex structures (e.g., lists, dicts, classes) you shouldn't use it for basic types like integers and strings. I have not yet come across a case where this was necessary anyways.</p>

<p class='section_header' id="conditions"><b>10. Conditions</b></p>

<p>Python has (of course) conditional statements:

<b><code>if</code></b>
<ul>
    <li>if the given condition evaluates to true, the following statements will be executed</li>
</ul>

<b><code>elif</code></b>
<ul>
    <li>if none of the previous conditions were true but the one given is, then the following statements will be executed</li>
</ul>

<b><code>else</code></b>
<ul>
    <li>if none of the previous conditions were true, the following statements will be executed</li>
</ul>

<b>!!! Conditions DO NOT introduce a new scope !!!</b></p>

In [25]:
number = 3

if type(number) != int:
    print('only integers allowed.')
    print("I'll take care of it!")
    number = int(number)
    
if number == 0:
    print('zero')
elif number == 1:
    print('one')
elif number == 2:
    print('two')
elif number > 2:
    # nested if's are a thing!
    if not number%3: # 0 evaluates to False
        print("It's dividable by three!")
        print("You won!")
    else:
        print("Try a number that is smaller by {}".format(number%3))
else:
    print("I don't like number smaller than zero.")
    print("They are always so negative.")

It's dividable by three!
You won!


<p class='section_header' id="loops_revisited"><b>11. Loops (Revistited)</b></p>

<b><code>for</code> loop</b>
<ul>
    <li>you can <code>continue</code> to the next iteration and skip all remaining statements</li>
    <li>you can <code>break</code> out of loops</li>
    <li>python <code>for</code> loops have an <code>else</code> block</li>
    <ul>
        <li>The block is executed only if no <code>break</code> occurred during the for loop</li>
    </ul>
</ul>

In [26]:
a_list = [1,2,5,7]

for an_element in a_list:
    if type(an_element) != int:
        print("{} is not an integer!".format(an_element))
        continue
        
    if not an_element%3:
        print('{} is dividable by 3'.format(an_element))
        print('I stop looking')
        break

    print('{} is NOT dividable by 3'.format(an_element))
else:
    print("Didn't find anything :(")

1 is NOT dividable by 3
2 is NOT dividable by 3
5 is NOT dividable by 3
7 is NOT dividable by 3
Didn't find anything :(


<p>Now that we know conditions. We can use another type of loop:</p>

<b><code>while</code> loop</b>
<ul>
    <li>iterate over content, while the initial condition evaluates to True</li>
    <li>can use <code>continue</code> in while loops</li>
    <li>can use <code>break</code> in while loops</li>
    <li>has an <code>else</code> block</li>
    <ul>
        <li>only executed if the condition evaluated to false</li>
        <li><code>break</code> or other "exits" won't trigger the <code>else</code> block</li>
    </ul>
</ul>

In [27]:
list_of_nums = [1,2,5,7,10,15]

while list_of_nums and list_of_nums[0] != 10:
    if type(list_of_nums[0]) != int:
        break
    
    del list_of_nums[0]

else:
    print("Either we've reached 10, or 10 is not in the list.")
    
print(list_of_nums)

Either we've reached 10, or 10 is not in the list.
[10, 15]


<p class='section_header' id="list_comp"><b>12. List Comprehension</b></p>

<p>A common thing is to use <code>for</code> loops and <code>if...else</code> blocks to create collections. That is commonly referred to as <b>list comprehension</b>.

For example, lets create a list that contains the squares of all integers from 0 to 9:</p>

In [28]:
squares = [i**2 for i in range(10)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


<p>What if we only want the squares that are divisable by 4?</p>

In [29]:
squares_div_4 = [ j**2 for j in range(10) if not j**2%4]
print(squares_div_4)

[0, 4, 16, 36, 64]


<p class='section_header' id="membership"><b>13. Membership</b></p>

<p>We can simplify the usage of collections further by using the membership operators <code>in</code> and <code>not in</code>.

<code>in</code> checks if the element on the left hand side is contained within the collection on the right hand side. This allows us to quickly check if an element is within a list. </p>

In [30]:
a_list = [1,2,3]
x = 2
y = 4

print("x in a_list:",x in a_list)
print("y in a_list:",y in a_list)
print("3 in a_list:",3 in a_list)

x in a_list: True
y in a_list: False
3 in a_list: True


<p>For dictionaries <code>in</code> checks if the element exists as a key.</p>

In [31]:
a_dict ={'a':2, 1:'b'}

print("'a' in a_dict:",'a' in a_dict)
print("'1' in a_dict:", 1 in a_dict)
print("'2' in a_dict:", 2 in a_dict)

'a' in a_dict: True
'1' in a_dict: True
'2' in a_dict: False


<p class='section_header' id="classes"><b>14. Classes</b></p>

<p>Classes can be thought of as blueprints for a container that stores particular variables and functions. Whenever we need such a container we just "instantiate" the blueprint. These containers are commonly called <b>objects</b> or <b>instances</b>.</p>

<ul>
    <li>Classes are defined using the <code>class</code> keyword.</li>
    <li>Functions usable by the class (i.e. member functions) are defined within the scope of the class by simply using the <code>def</code> keyword.</li>
    <li>You create an instance by using the class name as a function and assigning the output to a variable.</li>
    <li><code>self</code> is the instance you created. Every non-static function within a class always takes <code>self</code> as the first argument.</li>    
</ul>

In [32]:
class Treasure(): #"Treasure" is just an arbitary name
    def open_it(self):
        print("You found: nothing!")
        
bad_treasure = Treasure()
bad_treasure.open_it()

You found: nothing!


<p>the <code>__init__(self,...)</code> function is the first function that is called every time a new instance is created for that instance: <code>self</code><p>
<ul>
    <li>this is not a constructor!</li>
    <li>you define what initial arguments your calls needs by defining them in the function header after self.</li>
</ul>

In [33]:
class Treasure(): #"Treasure" is just an arbitary name
    def __init__(self, content):
        self.content = content
    
    def open_it(self):
        print("You found: {}!".format(self.content))
             
bad_treasure = Treasure('a blueprint')
bad_treasure.open_it()

You found: a blueprint!


<p>Python supports inheritance<p>
<ul>
    <li>You add base classes by listing them in the parenthesis after the class name.</li>
    <li>By default every class in python 3 inherits the <code>object</code> class i.e., <code>class AClass():</code> is the same as <code>class AClass(object):</code></li>
    <li>Multiple inheritance is also possible.</li>
</ul>

<p>Function overriding is done by simply re-defining the base function in the the child class.<p>
<ul>
    <li>if you want to call the base function use <code>super()</code></li>
    <li>in case of multiple inheritance explicit base function calls are a better idea: <code>Base.func(self,...)</code></li>
</ul>

<p class='section_header' id="duck_typing"><b>15. Duck Typing</b></p>

<p>Python uses "duck typing"

<ul>
    <li>if it walks like a duck and it quacks like a duck, then it must be a duck!</li>
</ul>

In other words, in the below program, if you have a method that expects a duck and you give it a duck everything is great. If you give it a penguin one of two things will happen:

<ul>
    <li>if the method asks the penguin to lay an egg</li>
    <ul>
        <li>everything will work out (... for now)</li>
    </ul>
    <li>if the method asks the penguin to fly</li>
    <ul>
        <li>the penguin will fall on it's face, just as your program</li>
    </ul>
</ul></p>

In [34]:
class Duck():
    def get_egg(self):
        print("PLOP! You got an egg!")

    def fly(self):
        print("Wheee! It's flying")
        
class Penguin():
    def get_egg(self):
        print("PLOP! You got an egg!")

def get_an_egg(duck):
    duck.get_egg()

def make_it_fly(duck):
    duck.fly()
    
doug = Duck()
get_an_egg(doug)
make_it_fly(doug)

penny = Penguin()
get_an_egg(penny)
make_it_fly(penny)

PLOP! You got an egg!
Wheee! It's flying
PLOP! You got an egg!


AttributeError: 'Penguin' object has no attribute 'fly'

<p class='section_header' id="casting"><b>16. Casting</b></p>

<p>Even if we strictly use duck typing, it makes sense to transform a variable of one type into another type. This is known as type <b>casting</b> and it's very easily done in Python (at least for the basic types).

For instance, if you expect a numerical value, but you just care for the integer part, you can simply cast it into an int.

<b>Be aware that casting can also go wrong.</b></p>

In [35]:
pos = 5

# No need for type checking or rounding / floor division
def move(distance=1):
    return pos - int(distance)

pos = move(2.1)
print(pos)

# this also works
print(type(int('2')))

# this also works
print(type(float('2.5')))

# but this throws an exception!
print(type(int('2.5')))

3
<class 'int'>
<class 'float'>


ValueError: invalid literal for int() with base 10: '2.5'

<p class='section_header' id="exceptions"><b>17. Exceptions</b></p>

<p>Exceptions occur whenever something doesn't go as planned, e.g., using penguins as ducks. We can "catch" such exceptions easily in python with the <code>try...except</code> construct.

If an exception occurs within a <code>try</code> block all subsequent statements within the block are skipped and a corresponding exception handler (i.e. a <code>except</code> block) is searched and evaluated.</p>

In [36]:
a = 1
b = 0

try:
    c= a/b
except ZeroDivisionError as err:
    print("you divided by zero")
    c = a
    
print(c)

you divided by zero
1


<p>There is the <code>finally</code> block, that will always be evaluated. Even if exceptions are not handled or new exceptions occur during exceptions handling.</p>

In [37]:
a = 1
b = 0

try:
    c= a/b
except ZeroDivisionError as err:
    print("you divided by zero")
    c = a
else:
    print("Everything went well")
finally:
    print("This code always happens!")
    
print(c)

you divided by zero
This code always happens!
1


<p>Exceptions are just class instances, so we can create our own. We throw any exception by using the keyword <code>raise</code>. </p>

In [38]:
class ThreeDivisionError(Exception):
    pass

a = 1
b = 3

try:
    if b == 3:
        raise ThreeDivisionError("We don't like 3s")
    c= a/b
except ZeroDivisionError as err:
    print("you divided by zero")
    c = a
else:
    print("Everything went well")
finally:
    print("This always happens!")
    
print(c)

This always happens!


ThreeDivisionError: We don't like 3s

<p>If you come from Java you might say: "But I won't have to use try...except statement too much anyway because I just check if everything is in order before I try something stupid."

Well... THIS ISN'T JAVA!

The python way teaches: "it's easier to ask for forgiveness than permission". Remember duck typing? <code>try..except</code> is the other end of it. 
<ul>
    <li>Assume everything works like you expect and be prepared if it doesn't!</li>
    <li>READ THE DOCUMENTATION!</li>
</ul></p>

<p class='section_header' id="modules"><b>18. Modules</b></p>

<p>Python modules offer functionalities e.g., functions and classes, that someone developed and published for anyone to use.

You can access these modules by using the <code>import</code> keyword. You can also alias the module/function by using <code>import ... as</code>.

If you know a piece of functionality from the module you want you can just import that specific function by using <code>from ... import</code>.

Let's import numpy:</p>

In [39]:
import numpy as np

<p>If you get an exception that the module 'numpy' doesn't exist you will have to install it in your conda environment.

<ul>
    <li>Open a new terminal.</li>
    <li>Activate your conda environment: <code id="code">conda activate [environment name]</code></li>
    <li>Install numpy: <code id="code">conda install numpy</code></li>
    <li>Try running the above cell again.</li>
</ul></p>

<p class='section_header' id="numpy"><b>19. Numpy (in a nutshell)</b></p>

<p>Numpy gives us access to a lot of great mathematical tools. It includes tools for linear algebra, matrix calculus, and stochastics/probability theory. Lets create some vectors and matrices.</p>

In [40]:
import numpy as np

# Lets create a numpy array
a = np.array([1,2,3])
print("\na:\n",a)

# if we add another dimensions its a row vector
row_vec = np.array([[1,2,3]])
print("\nrow_vec:\n",row_vec)

# transposing a row_vector leads to a column vector
col_vec = row_vec.T
print("\ncol_vec:\n",col_vec)

# we can also directly specify a column vector
col_vec = np.array([[1],[2],[3]])
print("\ncol_vec:\n",col_vec)

# and transposing that one brings us back to a row vector
row_vec = col_vec.T
print("\nrow_vec:\n",row_vec)

# we can define a matrix the same way
mat = np.array([[0,0,1],[1,0,0],[0,1,0]])
print("\nmat:\n",mat)

# we can compute dot/inner products using numpy.dot
inner_prod = np.dot(col_vec.T,col_vec)
print("\ninner:\n",inner_prod)

# this way we can also compute the outer product
outer_prod = np.dot(col_vec,col_vec.T)
print("\nouter:\n",outer_prod)

# and we can also use this for matrix multiplication
vec_times_mat = np.dot(mat,col_vec)
print("\nvec_times_mat:\n",vec_times_mat)

mat_times_mat = np.dot(mat,mat)
print("\nmat_times_mat:\n",mat_times_mat)


a:
 [1 2 3]

row_vec:
 [[1 2 3]]

col_vec:
 [[1]
 [2]
 [3]]

col_vec:
 [[1]
 [2]
 [3]]

row_vec:
 [[1 2 3]]

mat:
 [[0 0 1]
 [1 0 0]
 [0 1 0]]

inner:
 [[14]]

outer:
 [[1 2 3]
 [2 4 6]
 [3 6 9]]

vec_times_mat:
 [[3]
 [1]
 [2]]

mat_times_mat:
 [[0 1 0]
 [0 0 1]
 [1 0 0]]


<p class='section_header' id="mutables"><b>20. Mutables as default values in functions</b></p>

<p>One more python weirdness... We know how to set default values for function arguments and so far it worked well with basic types. But what happens if we use mutable objects as defaults? </p>

In [41]:
def add_ele_to_list(ele, a_list=[]):
    a_list.append(ele)
    return a_list
    
#Lets add elements to two different lists
l5 = add_ele_to_list(5)
l7 = add_ele_to_list(7)

# we expect l5 and l7 to be two independent lists
# with the values 5 and 7 respectively
print("l5:",l5)
print("l7:",l7)

# why do both lists contain the both numbers?
# lets check the ids
print("id(l5):",id(l5))
print("id(l7):",id(l7))

# They are the same list!

l5: [5, 7]
l7: [5, 7]
id(l5): 2172964404424
id(l7): 2172964404424


<p>This behavior happens because the function header is evaluated only once when the functions is created. Therefore, the default list is not created every time the function is called but rather only once and every time the function is called with the default value, the same list is used.

What can we do about it? Don't use mutable objects as default values. Use <code>None</code> instead!</p>

In [42]:
def add_ele_to_list(ele, a_list=None):
    if a_list is None:
        a_list=[]
    a_list.append(ele)
    return a_list
    
#Lets add elements to two different lists
l5 = add_ele_to_list(5)
l7 = add_ele_to_list(7)

# we expect l5 and l7 to be two independent lists
# with the values 5 and 7 respectively
print("l5:",l5)
print("l7:",l7)

# and that is excatly what happens!
# lets check the ids
print("id(l5):",id(l5))
print("id(l7):",id(l7))

# They are the same list!

l5: [5]
l7: [7]
id(l5): 2172964588040
id(l7): 2172964587912


<p class='section_header' id="wrap_up"><b>21. Wrap Up</b></p>

<p>We have learned a lot about python and there is still so much more to learn and to understand. However, what you learned here should be sufficient for this tutorial and with time you will learn all the features, tricks and quirks of Python.</p>

<p>From now on we will talk about specific functionalities of specific modules only once we encounter situations where we need them. For instance, once we start with the robotics introduction we will have a closer look at vectors and matrices and therefore at the <code>numpy</code> module! </p>

<p>To finish up, <b>make sure you go back to Github_Classroom_Tutorial</b> and read the note about how to update assignments!</p>

In [43]:
# Custom CSS styling.
from IPython.core.display import HTML

HTML(open("./styles/custom.css", "r").read())